---
services:
  boca-api:
    build: .
    image: boca-api
    container_name: boca-api
    volumes:
      - .:/usr/app
    depends_on:
      boca-postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - LISTEN_PORT=3000
      - TOKEN_EXPIRES_IN_SECONDS=1800
      - PASSWORD_SALT=v512nj18986j8t9u1puqa2p9mh
      - DB_PORT=5432
      - DB_HOST=boca-postgres
      - DB_NAME=bocadb
      - DB_USER=bocauser
      - DB_PASSWORD=dAm0HAiC
      # privileged boca user
      - DB_SUPER_USER=bocauser
      - DB_SUPER_PASSWORD=dAm0HAiC
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail -s --output /dev/null http://localhost:$${LISTEN_PORT}/api/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 4

  boca-postgres:
    image: postgres
    container_name: boca-postgres
    restart: unless-stopped
    volumes:
      - boca-api-validation:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      # Database configuration
      # privileged boca user
      - POSTGRES_USER=bocauser
      - POSTGRES_PASSWORD=dAm0HAiC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 4

  boca-web:
    image: ghcr.io/joaofazolo/boca-docker/boca-web
    container_name: boca-web
    privileged: true
    restart: unless-stopped
    depends_on:
      boca-postgres:
        condition: service_healthy
      boca-api:
        condition: service_healthy
    environment:
      # Database configuration
      - DB_HOST=boca-postgres
      - DB_PORT=5432
      - DB_NAME=bocadb
      # unprivileged boca user
      - DB_USER=bocauser
      - DB_PASSWORD=dAm0HAiC
      # privileged boca user
      - DB_SUPER_USER=bocauser
      - DB_SUPER_PASSWORD=dAm0HAiC
      # initial password that is used by the admin user (web app)
      # If not set, the default value is 'boca'
      - BOCA_PASSWORD=boca
      # secret key to be used in HTTP headers
      # MUST set it with any random large enough sequence
      - BOCA_KEY=GG56KFJtNDBGjJprR6ex
    ports:
      - "8000:80"

  boca-jail:
    image: ghcr.io/joaofazolo/boca-docker/boca-jail
    container_name: boca-jail
    privileged: true
    restart: unless-stopped
    depends_on:
      - boca-postgres
    environment:
      # Database configuration
      - DB_HOST=boca-postgres
      - DB_PORT=5432
      - DB_NAME=bocadb
      # unprivileged boca user
      - DB_USER=bocauser
      - DB_PASSWORD=dAm0HAiC
      - PASSWD=dAm0HAiC

volumes:
  boca-api-validation:
    driver: local
