services:
  boca-postgres:
    ports: 
        - 5432:5432
    volumes: 
        - db-data:/var/lib/postgresql/data
  app:
    build: .
    container_name: boca_api
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
    links:
      - boca-postgres
    depends_on:
      - boca-postgres

  boca-adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - boca-postgres
    ports:
        - 8080:8080
    links:
      - boca-postgres

volumes:
    db-data:
      driver: local