services: 

  boca-api:
    build: .
    image: boca-api
    volumes:
      - .:/usr/app
    links:
      - boca-postgres
    depends_on:
      boca-postgres:
        condition: service_healthy

  boca-web:
    image: ghcr.io/joaofazolo/boca-docker/boca-web
    privileged: true
    restart: unless-stopped
    depends_on:
      boca-postgres:
        condition: service_healthy
    environment:
      - DB_HOST=boca-postgres
      # initial password that is used by the admin user (web app)
      # If not set, the default value is 'boca'
      - BOCA_PASSWORD=boca
      # secret key to be used in HTTP headers
      # MUST set it with any random large enough sequence
      - BOCA_KEY=GG56KFJtNDBGjJprR6ex

  boca-postgres:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
