---
name: Lint code base

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      # Checkout a repository under $GITHUB_WORKSPACE,
      #  so the workflow can access it.
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Repository name with owner. For example, actions/checkout.
          # Default: ${{ github.repository }}
          repository: "${{ github.repository }}"
          # Full git history is needed to get a proper list of
          #  changed files within `super-linter`
          fetch-depth: 0

      # Run a Super-Linter against code base
      # https://github.com/marketplace/actions/super-linter
      - name: Lint repo code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_PHP: false
          VALIDATE_JSCPD: false
          LOG_LEVEL: WARN
          EDITORCONFIG_FILE_NAME: .editorconfig
          LINTER_RULES_PATH: /
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
