name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  api:
  
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: yarn install

      - name: Executar script de testes
        run: yarn test:api
