---
name: Use Cases Test

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  usecases:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: yarn install

      - name: Build da imagem docker da aplicação
        run: docker build -t boca-api .

      - name: Subir contêineres
        run: yarn test:docker:up

      - name: Health check na aplicação
        run: yarn test:health

      - name: Script de testes
        run: yarn test:usecases

      - name: Descer contêineres
        run: yarn test:docker:down
